platform :ios, '9.0'

target 'Runner' do
  
  use_frameworks!
  inhibit_all_warnings!
  
  #SDK
  pod 'NVSDK', :path=>'LocalPods/NVSDK/NVSDK.podspec'
  #SVProgressHUD
  pod 'SVProgressHUD', :path=>'LocalPods/SVProgressHUD/SVProgressHUD.podspec'
  #ALAssetsLibrary
  pod 'ALAssetsLibrary', :path=>'LocalPods/ALAssetsLibrary/ALAssetsLibrary.podspec'
  
  pod 'lottie-ios', '2.5.3'
  
  pod 'SDWebImage'                         , '5.9.1'

end

#deal with target has transitive dependencies that include statically linked binaries
pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
